---
- name: Change Windows Local Admin Password
  hosts: windows
  gather_facts: false

  tasks:

    - name: Change local Admin password
      ansible.windows.win_user:
        name: Admin
        password: "{{ 1n9pp9dmin4# }}"
        state: present
        update_password: always
      no_log: true
